# Generated by Django 5.0.1 on 2024-02-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orphan',
            name='child_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
